# general settings
name: MBAN_5_11_15_X3
model_type: SRModel
scale: 3
num_gpu: 1
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: D:\ablation_study\dataset\DF_HR_sub.lmdb
    dataroot_lq: D:\ablation_study\dataset\DF_LR_bicubic_X3_sub.lmdb
    io_backend:
      type: lmdb
    pin_memory: True

    gt_size: 144
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 20
    batch_size_per_gpu: 64
    dataset_enlarge_ratio: 100
    prefetch_mode: cuda


  val:
    name: DIV2K_val
    type: PairedImageDataset
    dataroot_gt: D:\ablation_study\dataset\DIV2K_valid_HR.lmdb
    dataroot_lq: D:\ablation_study\dataset\DIV2K_valid_LR_bicubic_X3.lmdb
    io_backend:
      type: lmdb


# network structures
network_g:
  type: MBAN
  num_in_ch: 3
  num_feat: 40
  d_atten: 64
  num_block: 14
  num_out_ch: 3
  scale: 3

# path
path:
#  auto_resume: ture
  pretrain_network_g: ~
  strict_load_g: ~
  resume_state: experiments/MBAN_5_11_15_X3/training_states/980000.state


# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [1000000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 1000000
  warmup_iter: -1  # no warm up


  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 3
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~
    entity: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29501