# general settings
name: MSAN_7_13_19_X4
model_type: SRModel
scale: 4
num_gpu: 1
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: E:/programming1/dataset/DF_HR_sub.lmdb
    dataroot_lq: E:/programming1/dataset/DF_LR_bicubic_X3_sub.lmdb
    io_backend:
      type: lmdb

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 10
    batch_size_per_gpu: 64
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: DIV2K_val
    type: PairedImageDataset
    dataroot_gt: E:/programming1/dataset/DIV2K_valid_HR/
    dataroot_lq: E:/programming1/dataset/DIV2K_valid_LR_bicubic_X3/X3/
    io_backend:
      type: disk


# network structures
network_g:
  type: MSAN
  num_in_ch: 3
  num_feat: 40
  d_atten: 64
  num_block: 15
  num_out_ch: 3
  scale: 4

# path
path:
#  auto_resume: ture
  pretrain_network_g: ~
  strict_load_g: ~
#  resume_state: C:\Users\3090\Desktop\VapSR-main\experiments\MSAN_7_15_21_X4\training_states\840000.state


# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [1000000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 1000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~
    entity: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29501